services:
  db_postgres_voting_go:
    image: postgres:12
    container_name: db_postgres
    environment:
      POSTGRES_PASSWORD: "postgres123"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "db_voting"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin_voting_go:
    image: dpage/pgadmin4
    container_name: db_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "user@test.com"
      PGADMIN_DEFAULT_PASSWORD: "postgres123"
    ports:
      - "8888:80"

  redis_voting:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis:/root/redis
    environment:
      - REDIS_PASSWORD=my-passwordRedis
volumes:
  pgdata: {}
  redis: {}
